version: '3.8' 

services:
  backend:
    image: todo_server:v1.0 
    ports:
      - "5000:5000" 
    depends_on:
      - mongo  

  frontend:
    image: todo_client:v1.0
    ports:
      - "5173:5173"
    depends_on:
      - backend 

  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017"


